### ISSUE TITLE
Use npm binaries from project's node_modules instead of global ones

### ISSUE THREAD

**Issue by pf1gura** [etkachev/nx-webstorm#2]
I don't have `ng cli` installed globally and schematics creation does not work for me

![image](https://user-images.githubusercontent.com/41795518/92792813-29d67100-f3ae-11ea-81d7-05792a3fe8f8.png)
The config above runs `ng generate @schematics/angular:enum --name=test --path=. --no-interactive` which fails with `fish: Unknown command: ng`

**Comment by etkachev** [comment]
this was closed by PR #11 .
@pf1gura I am currently working on sending out another [release](https://github.com/etkachev/nx-webstorm/pull/12), might be a couple day's before Jetbrains approves and you see the new update in the plugin. Keep an eye on the update and let us know if you still have problems. Thanks!
