### ISSUE TITLE
Allow to set custom location of nx.json or angular.json

### ISSUE THREAD

**Issue by fasidOnGit** [etkachev/nx-webstorm#42]
We are on a large maven monorepo where one of the maven submodule is Nx workspace (_yeah I know_), Basically, my root project directory doesn't have `nx.json` or `angular.json`. While the sub folders have them. because of which I cannot use this plugin to generate stuff using Nx.

I'd really appreciate if we could can set the Custom path for `nx.json` or `angular.json` via, `Tools -> Nx Plugin Settings` in Webstrom/IntelliJ.

**Comment by etkachev** [comment]
Hello @fasidOnGit! Yea I can take a look at this and see how quickly I can add this feature 😁

**Comment by fasidOnGit** [comment]
@etkachev  I gave it a thought, it shouldn't be custom location of `nx.json`. it.should be custom location of project folder where `nx.json` is in root. 

Because IIUC, that's how everything works in `nx` cli.

**Comment by etkachev** [comment]
@fasidOnGit yea that's what I was thinking. Just being able to configure the project folder... by default it would be `/`. But in your case you can set it to the directory in which your `nx.json` is located.

**Comment by etkachev** [comment]
@fasidOnGit I merged in the changes. It has not been published over to jetbrains plugins marketplace, but you can manually install the updated plugin, and let me know if this is what fits your needs. Once I hear from you that this is what you were looking for, I will submit release to jetbrains
[nx-webstorm-0.8.0.zip](https://github.com/etkachev/nx-webstorm/files/5857616/nx-webstorm-0.8.0.zip)

**Comment by fasidOnGit** [comment]
@etkachev Hello, Thanks for the quick fix. I did set my sub-folder like `/mydir` But, still I see `Nx` disabled

**Comment by etkachev** [comment]
Have you tried restarting the ide? I noticed it sometimes requires restart after updating the root directory in settings

**Comment by etkachev** [comment]
Also does the nx tool tab show up on the right side?

**Comment by fasidOnGit** [comment]
@etkachev Nope it doesn't.

**Comment by fasidOnGit** [comment]
@etkachev I like the VSCode Nx extension. When I open my project in VsCode and switch to `Nx Console`. It asks me to select the Nx Worspace directory(since, my project root is not a Nx Workspace) and We can choose any Nx Workspace(Even outside the project dir). and after I select I see Nx cosole generate options which will be run in the selected project dir

Try opening a Non-Nx project in VsCode and switch to `Nx Console` things will make more sense then. and I'd vote for the same behaviour here :)

**Comment by etkachev** [comment]
> @etkachev Nope it doesn't.

That's strange. I did test on a local repo that had the nx workspace a couple directories down.... like example below. You will see where the nx.json is located, which is what it is looking for. Is this a similar directory pattern you have setup?
<img width="1920" alt="Screen Shot 2021-01-23 at 10 42 49 PM" src="https://user-images.githubusercontent.com/9970746/105623197-bd906300-5dcc-11eb-9256-8717706ab2d3.png">

**Comment by fasidOnGit** [comment]
sorry missclick

**Comment by fasidOnGit** [comment]
@etkachev It does work when i create a new project dir and just nest an nx project like you have did,
![image](https://user-images.githubusercontent.com/27940795/105624351-143a8300-5e47-11eb-92e0-1ed208e88998.png)


But, it doesn't work for my pre-existing intellij workspace (a maven project)

**Comment by etkachev** [comment]
Ok. I'll try to replicate the problem locally as much as I can. I will create a new maven project, then add a sub-directory within it and generate a new nx project. Let me know if there is anything else I should try in order to replicate the problem as much as I can. Thanks

**Comment by etkachev** [comment]
@fasidOnGit So I created a clean maven project and generated a new nx project within that. And things seemed to still work. Example below:
<img width="1536" alt="Screen Shot 2021-01-24 at 9 19 25 PM" src="https://user-images.githubusercontent.com/9970746/105664702-2ab5fe00-5e8a-11eb-9b41-22e0c3c07a72.png">

One thing I did notice is that you have an `.idea` folder at the root of your maven project. But also another `.idea` folder within the nx directory as well? Do you think that might cause some issues? Also what other plugins do you currently have installed?

**Comment by fasidOnGit** [comment]
@etkachev I removed the nested `.idea` yet, I still see the issue. Also, I did disable `Nx Console Idea` plugin just to be on the safe side. Nothing worked. But I guess, It could be that I have a corrupted `.idea`.

IMHO, this issue can be closed. I will open my project as a fresh workspace. Thanks for the quick fix here :)

**Comment by etkachev** [comment]
Ok. So does it work when you open your maven project as fresh workspace. And try to run the schematics from the nx sub-directory? If that does work, then I'm assuming I should be safe to publish this version to JetBrains? I can continue improving the experience as we go along 😁

**Comment by fasidOnGit** [comment]
Yes I confirm that when opening a fresh workspace even with maven I can see it works as expected.

![image](https://user-images.githubusercontent.com/27940795/105676431-81feb180-5f10-11eb-8a9d-e8c981902ea9.png)

**Comment by etkachev** [comment]
Great! I'll send out the new release to Jetbrains soon! I'm hoping to get in some more features in the near future like running the other nx commands other than generate. It's just been busy lately. Thank you for using the plugin 😄

**Comment by etkachev** [comment]
Closing issue. Latest 0.8.0 version of the plugin has been released to Jetbrains marketplace.
