### ISSUE TITLE
Support $id in schema.json for finding schematics

### ISSUE THREAD

**Issue by julien-vidal** [etkachev/nx-webstorm#71]
**Is your feature request related to a problem? Please describe.**

In last version of json-schema, it seems the id property of a schema has been deprecated in favor of [$id](https://json-schema.org/understanding-json-schema/structuring.html#the-id-property).
It could be interesting to add this property for detect new json-schema and ensure long term schematics detection.

**Describe the solution you'd like**
Handle id and $id property for json-schema

**Additional context**
It seems schematics detection comes from this [file](https://github.com/etkachev/nx-webstorm/blob/master/src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt).

**Comment by etkachev** [comment]
Hello! Yes I can do an update to support this. Thank you for pointing this out.

**Comment by etkachev** [comment]
@julien-vidal . Quick question. Were you talking in regards to custom schematics within an Nx workspace? Or plain angular project with custom schematics?

**Comment by julien-vidal** [comment]
I'm talking about custom schematics within an Nx workspace.

Well, as far I can understand Kotlin code, it seems the issue will only happen for custom nx schematics.

The way you detect custom nx schematic from this location [file](https://github.com/etkachev/nx-webstorm/blob/master/src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt) seems different from how you detect them in node_module for example ([file](https://github.com/etkachev/nx-webstorm/blob/master/src/main/kotlin/com/github/etkachev/nxwebstorm/utils/FindSchematics.kt#L122)).

The first one seems based on id, which is now deprecated in favor of $id.
The other seems to be based on description.

Don't know if it can help you ^^.

**Comment by etkachev** [comment]
I merged in an update, feel free to download latest unreleased version of the plugin (0.9) from the [releases page](https://github.com/etkachev/nx-webstorm/releases). Let me know if it works locally for you with the new `$id` check.

**Comment by julien-vidal** [comment]
Really cool ! I'll test it as soon the 0.9 will be rolled out.

For now, it seems [releases page](https://github.com/etkachev/nx-webstorm/releases) don't have the 0.9.
Webstorm page doesn't have it too ...

**Comment by etkachev** [comment]
Oh I just realized that Draft releases aren't available to the public 😅 . I manually uploaded the artifacts to this comment.
[nx-webstorm-0.9.zip](https://github.com/etkachev/nx-webstorm/files/6670839/nx-webstorm-0.9.zip)

Let me know if you're able to test it out.

**Comment by julien-vidal** [comment]
No problem ! 😄 

I tested it and seems work perfectly !
Our customs nx schematics are detected with old `id` and new one `$id`.

Thanks a lot for your reactivity 😉 .
I wait for official 0.9 now ^^.

**Comment by etkachev** [comment]
Great! I just submitted plugin for pending reviewal... Should see it in marketplace sometime early next week.

**Comment by etkachev** [comment]
0.9 should be published and available for update in jetbrains marketplace. Closing this ticket. Let me know if there is anything else. Thanks again.
