### ISSUE TITLE
Action bar disappeared if there's no option for a workspace-schematic

### ISSUE THREAD

**Issue by gogoout** [etkachev/nx-webstorm#73]
First of all, thanks for the great plugin.

## Current Behavior
For a workspace-schematic with options, it shows the ui correctly
![image](https://user-images.githubusercontent.com/7570175/131776827-eab6937a-4b5b-45cd-af9a-cc96ee396776.png)
But for the one without options, the action bar disappeared
![image](https://user-images.githubusercontent.com/7570175/131776997-0e5b6d9b-da5b-4bb7-bdc8-efe93b4cb8d4.png)

## How to Reproduce
1. create a workspace-schematic
2. replace the `schema.json` with something like this
```json
{
	"$schema": "http://json-schema.org/schema",
	"id": "YOUR-SCHEMA-NAME",
	"type": "object"
}
```
3. run the schematic in plugin 

## Expected Behavior
Action bar should appear just as standard schematics without options
![image](https://user-images.githubusercontent.com/7570175/131777242-dc907892-288b-4445-8fe5-55d002d3c1db.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Catalina]
 - Webstorm version [e.g. 2021.2.1]

**Comment by gogoout** [comment]
On a bit research I found that adding an empty properties fix the problems

**Comment by etkachev** [comment]
@gogoout Ah ok. Thanks for the heads up. I will keep an eye on it, if it becomes more of a problem.
