### ISSUE TITLE
Load default values from workspace.json (angular)

### ISSUE THREAD

**Issue by petterhoel** [etkachev/nx-webstorm#75]
**workspace.json preferences to be default in plugin gui**
I (nearly) always want changedetection to be OnPush and style to be scss. It is not a hard to change it in the gui, but It would be a slick quality of life thing if the gui used the defaults I put in the `workspace.json`. 

**Solution**
Changedetection and styles are the values that is an issue for me, but I would love for the plugin to load any any defaults that can be set in workspace.json/angular.json and fall back to whatever nx/angular default are if none is explicitly set in workspace.json/angular.json. 

Here are screenshots of current behavior and a repo that can be used as a sandbox. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1263775/134769076-4a15b325-e638-43f3-95a2-fbb5874d8e8a.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1263775/134769080-ee83923c-1ef1-45d7-8d8d-506b79943705.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1263775/134769090-ff62290c-7ae4-410b-a77d-990c88b46679.png">

Also: I use your plugin every day. Thank you so much for making it 🥇

**Comment by etkachev** [comment]
Hello @petterhoel! Thanks for bring this up. I can add this feature to my plugin, but based on your screenshots, you might be using this plugin instead right? https://github.com/iguissouma/nx-console-idea-plugin

**Comment by petterhoel** [comment]
You are right indeed. I had no idea there was two plugins 🤦‍♂️ So sorry 😃
