### ISSUE TITLE
nx-webstorm is not available in webstorm 2022.1 beta

### ISSUE THREAD

**Issue by ambeur** [etkachev/nx-webstorm#86]
Hi! There is no nx-webstorm plugin in marketplace in webstorm 2022.1 beta. Do you have any plans to add support for newer versions of webstorm?

**Comment by etkachev** [comment]
Sorry still waiting on Jetbrains to officially release Intellij Ultimate 2022. It's still in RC, but keeping an eye on when it will be available for plugin updates

**Comment by abdul-alim** [comment]
> Sorry still waiting on Jetbrains to officially release Intellij Ultimate 2022. It's still in RC, but keeping an eye on when it will be available for plugin updates

It is released officially now.

**Comment by etkachev** [comment]
The plugins for webstorm depend on on latest released version of Intellij Ultimate which is still on previous version: https://www.jetbrains.com/idea/download/

But trying to get around it by specifying a EAP-SNAPSHOT version.

**Comment by etkachev** [comment]
Uploaded the plugin updates to marketplace, should have it approved next couple days. In the meantime you can manually install the update from the artifacts here: https://github.com/etkachev/nx-webstorm/releases/tag/v0.9.3
