### ISSUE TITLE
The plugin is not compatible with the latest IntelliJ IDEA 2022.1 Version.

### ISSUE THREAD

**Issue by m-evasys** [etkachev/nx-webstorm#88]
The plugin is not compatible with the latest IntelliJ IDEA 2022.1 Version.

**Comment by etkachev** [comment]
Hello! Yea I just got a PR merged in that updates that and should be submitted to plugin store soon

**Comment by etkachev** [comment]
Uploaded the plugin updates to marketplace, should have it approved next couple days. In the meantime you can manually install the update from the artifacts here: https://github.com/etkachev/nx-webstorm/releases/tag/v0.9.3
