### ISSUE TITLE
Issue with re-running generate command from nx console when integrated terminal window is opened

### ISSUE THREAD

**Issue by fyodorio** [etkachev/nx-webstorm#95]
## Current Behavior
When I run some `generate` command in nx console in Webstorm it opens the integrated terminal window (or tabs of it, if it's dry run and simple run). If after that I run another command, it doesn't run until I close the already opened terminal window.

## How to Reproduce
1. Go to nx console plugin view
2. Choose `generate` and one of the schematics
3. Wait until it finishes successfully, do some random stuff
4. Try to run some other `generate` command for another schematic while the terminal window is still open
5. Nothing happens

## Expected Behavior
The command should successfully run repeatedly even if the terminal window is still opened

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Webstorm version 2022.1.1 (had the same issue in previous versions, at least in 2021)

## Additional context
Looks like the problem persists even if I run something different in the same terminal windows (dry/simple) between nx command run attempts. So only closing the terminal window helps to run nx generate again.

**Comment by etkachev** [comment]
Hello @fyodorio !!

Good to hear from you. Yea I was trying to run locally and had issues reproducing 🤔 
I tried several generators and reran several times with it running successfully. Trying to see what else might be happening.

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/9970746/171234035-e3a5c29e-f8ca-4b71-8d9b-3f9ae7243c3c.png">

**Comment by fyodorio** [comment]
Hey man, I have recorded the video of the issue finally (sorry it took quite some time), will send you on twitters, I hope it will help. But honestly speaking, I have no idea what could cause that except for some plugin/extension conflict (terminal shell might be the case as well, but shouldn't be, because it's not the shell which is responsible for the terminal window itself or opening/closing it, right? anyway, it's zsh). So if it doesn't reproduce for you, I'm totally OK with closing the issue, as it's not blocking, just a bit confusing, and I thought it might be the case for others as well.

**Comment by etkachev** [comment]
I also wanted to let you know about slowly deprecating this plugin in favor for the official on by Nrwl: https://plugins.jetbrains.com/plugin/21060-nx-console

**Comment by fyodorio** [comment]
That makes sense, thanks for the heads up. And thanks for the great plugin anyway Edward, I use it still 👍

**Comment by etkachev** [comment]
Yea makes it easier for me so I don't have to keep up with the maintenance 😅
